/* This file is autogenerated, do not edit, changes will be lost! */
#ifndef BOARD_CFG_H
#define BOARD_CFG_H (1)

/* === BOARD INCLUDES === */
#if defined(im240a)
# define BOOTLOADER_ADDRESS (0x0)
# include "boards/board_wimod.h"

#elif defined(im240a_eval)
# define BOOTLOADER_ADDRESS (0x0)
# include "boards/board_wimod.h"

#elif defined(tiny230) || defined(tiny231)
# define BOOTLOADER_ADDRESS (0x0)
# include "boards/board_tiny230.h"

#elif defined(lgee231)
# define BOOTLOADER_ADDRESS (0xc00)
# include "boards/board_lgee.h"

#elif defined(museIIrfa)
# define BOOTLOADER_ADDRESS (0xf000)
# include "boards/board_museIIrfa.h"

#elif defined(stb128rfa1)
# define BOOTLOADER_ADDRESS (0xf000)
# include "boards/board_stbrfa1.h"

#elif defined(dracula)
# define BOOTLOADER_ADDRESS (0xf000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (57600)
# endif
# include "boards/board_airdmx.h"

#elif defined(lgee231_v2)
# define BOOTLOADER_ADDRESS (0xc00)
# include "boards/board_lgee.h"

#elif defined(stb256rfr2)
# define BOOTLOADER_ADDRESS (0x1f000)
# include "boards/board_stbrfa1.h"

#elif defined(bat)
# define BOOTLOADER_ADDRESS (0xf000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (57600)
# endif
# include "boards/board_airdmx.h"

#elif defined(stkm8)
# define BOOTLOADER_ADDRESS (0x0)
# include "boards/board_stkm8.h"

#elif defined(stkm16)
# define BOOTLOADER_ADDRESS (0x1c00)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (115200)
# endif
# include "boards/board_stkm16.h"

#elif defined(bitbean)
# define BOOTLOADER_ADDRESS (0xf000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (38400)
# endif
# include "boards/board_wdba1281.h"

#elif defined(zgbt1281a2nouart)
# define BOOTLOADER_ADDRESS (0xf000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (38400)
# endif
# include "boards/board_zgbta2.h"

#elif defined(zgbt1281a2uart1)
# define BOOTLOADER_ADDRESS (0xf000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (38400)
# endif
# include "boards/board_zgbta2.h"

#elif defined(zgbt1281a2uart0)
# define BOOTLOADER_ADDRESS (0xf000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (38400)
# endif
# include "boards/board_zgbta2.h"

#elif defined(any900st) || defined(any2400st)
# define BOOTLOADER_ADDRESS (0xf000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (38400)
# endif
# include "boards/board_any.h"

#elif defined(any900) || defined(any2400)
# define BOOTLOADER_ADDRESS (0xf000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (38400)
# endif
# include "boards/board_any.h"

#elif defined(wdba1281) || defined(mnb900)
# define BOOTLOADER_ADDRESS (0xf000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (38400)
# endif
# define HAS_SENSOR_MCU_VTG (1)
# include "boards/board_wdba1281.h"

#elif defined(ics230_12) || defined(icm230_12c)
# define BOOTLOADER_ADDRESS (0xf000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (38400)
# endif
# include "boards/board_ict_11.h"

#elif defined(icm230_11) || defined(icm230_12a) || defined(icm230_12b)
# define BOOTLOADER_ADDRESS (0xf000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (38400)
# endif
# include "boards/board_ict_11.h"

#elif defined(ics230_11)
# define BOOTLOADER_ADDRESS (0xf000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (38400)
# endif
# include "boards/board_ict_11.h"

#elif defined(ict230)
# define BOOTLOADER_ADDRESS (0xf000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (38400)
# endif
# include "boards/board_ict230.h"

#elif defined(ravrf230a) || defined(ravrf230b)
# define BOOTLOADER_ADDRESS (0xf000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (9600)
# endif
# include "boards/board_ravrf.h"

#elif defined(rzusb)
# define BOOTLOADER_ADDRESS (0xf000)
# include "boards/board_rzusb.h"

#elif defined(zgbh230) || defined(zgbh231) || defined(zgbh212)
# define BOOTLOADER_ADDRESS (0xf000)
# include "boards/board_zgbl.h"

#elif defined(zgbl230) || defined(zgbl231) || defined(zgbl212)
# define BOOTLOADER_ADDRESS (0xf000)
# include "boards/board_zgbl.h"

#elif defined(derftorcbrfa1)
# define BOOTLOADER_ADDRESS (0xf000)
# include "boards/board_rbbrfa1.h"

#elif defined(rbb128rfa1)
# define BOOTLOADER_ADDRESS (0xf000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (38400)
# endif
# include "boards/board_rbbrfa1.h"

#elif defined(rbb230) || defined(rbb230b) || defined(rbb231) || defined(rbb212) || defined(rbb232) || defined(rbb233)
# define BOOTLOADER_ADDRESS (0xf000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (38400)
# endif
# include "boards/board_rbb.h"

#elif defined(wprog)
# define BOOTLOADER_ADDRESS (0xf000)
# include "boards/board_derfa.h"

#elif defined(xxo)
# define BOOTLOADER_ADDRESS (0xf000)
# define HAS_SENSOR_MCU_VTG (1)
# define HAS_SENSOR_MCU_T (1)
# include "boards/board_derfa.h"

#elif defined(pinoccio)
# define BOOTLOADER_ADDRESS (0x1f000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (115200)
# endif
# include "boards/board_derfa.h"

#elif defined(zigduino)
# define BOOTLOADER_ADDRESS (0xf000)
# include "boards/board_derfa.h"

#elif defined(radiofaro_v1)
# define BOOTLOADER_ADDRESS (0xf000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (38400)
# endif
# include "boards/board_derfa.h"

#elif defined(radiofaro)
# define BOOTLOADER_ADDRESS (0xf000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (57600)
# endif
# define HAS_SENSOR_MCU_VTG (1)
# define HAS_SENSOR_MCU_T (1)
# include "boards/board_derfa.h"

#elif defined(raspbee)
# define BOOTLOADER_ADDRESS (0x1f000)
# include "boards/board_derfa.h"

#elif defined(rdk230) || defined(rdk230b) || defined(rdk231) || defined(rdk212) || defined(rdk232) || defined(rdk233)
# define BOOTLOADER_ADDRESS (0xf000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (38400)
# endif
# define HAS_SENSOR_MCU_VTG (1)
# include "boards/board_rdk230.h"

#elif defined(stb230) || defined(stb230b) || defined(stb231) || defined(stb212) || defined(stb232) || defined(stb233)
# define BOOTLOADER_ADDRESS (0xf000)
# define HAS_SENSOR_MCU_VTG (1)
# include "boards/board_stb.h"

#elif defined(cbb230) || defined(cbb230b) || defined(cbb231) || defined(cbb212) || defined(cbb232) || defined(cbb233)
# define BOOTLOADER_ADDRESS (0x0)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (9600)
# endif
# include "boards/board_cbb2xx.h"

#elif defined(derfa1)
# define BOOTLOADER_ADDRESS (0xf000)
# define HAS_SENSOR_MCU_VTG (1)
# define HAS_SENSOR_MCU_T (1)
# include "boards/board_derfa.h"

#elif defined(derfn128u0) || defined(derfn128)
# define BOOTLOADER_ADDRESS (0xf000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (57600)
# endif
# define HAS_SENSOR_MCU_VTG (1)
# define HAS_SENSOR_MCU_T (1)
# include "boards/board_derfa.h"

#elif defined(derfn256u0) || defined(derfn256u0pa)
# define BOOTLOADER_ADDRESS (0x1f000)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (57600)
# endif
# define HAS_SENSOR_MCU_VTG (1)
# define HAS_SENSOR_MCU_T (1)
# include "boards/board_derfa.h"

#elif defined(psk230) || defined(psk230b) || defined(psk231) || defined(psk212) || defined(psk232) || defined(psk233)
# define BOOTLOADER_ADDRESS (0xf000)
# define HAS_SENSOR_MCU_VTG (1)
# include "boards/board_stk541.h"

#elif defined(ibdt212)
# define BOOTLOADER_ADDRESS (0x7800)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (38400)
# endif
# include "boards/board_ibdt.h"

#elif defined(ibdt231)
# define BOOTLOADER_ADDRESS (0x7800)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (38400)
# endif
# include "boards/board_ibdt.h"

#elif defined(ibdt232)
# define BOOTLOADER_ADDRESS (0x7800)
# if !defined(HIF_DEFAULT_BAUDRATE)
#  define HIF_DEFAULT_BAUDRATE (38400)
# endif
# include "boards/board_ibdt.h"

#elif defined(muse231)
# define BOOTLOADER_ADDRESS (0xc00)
# define HAS_SENSOR_MCU_VTG (1)
# define HAS_SENSOR_SHT21_T (1)
# define HAS_SENSOR_SHT21_RH (1)
# include "boards/board_muse231.h"

#elif defined(rose231)
# define BOOTLOADER_ADDRESS (0x3c00)
# include "boards/board_rose231.h"

#elif defined(midgee)
# define BOOTLOADER_ADDRESS (0xc00)
# include "boards/board_midgee.h"

#elif defined(museII232)
# define BOOTLOADER_ADDRESS (0x3800)
# include "boards/board_museII232.h"

#else
# error "BOARD_TYPE is not defined or wrong"
#endif

#endif /*BOARD_CFG_H*/
